name: EarthScopeTest
title: (from main _config.yamal)fetch-scripts - command line access to seismic data
markdown: kramdown
permalink: pretty
remote_theme: md-es/theme_ghpages
github_corner_link: https://global.link
